language: java
dist: trusty
script:
  gradle build
deploy:
  provider: releases
  api_key:
    secure: GQiAwlhIHQP8rG/dpq2AU8yeuiH7RWvV3SjNy7n2GJfwGrZ5FpJ3JQ75jT5yzeDFS6sEwR2N0yGJ+w3X7bIUVTtWDJp/q2hj8nCPXerHIKSJrSSjwcX1MWl701LCojCTINuDfbi+9sFfkJnvdRM0GUzZFy70Av3IAskiZ6fr1M5moLF1oHRM+0gsXYGjXrFJHkyqMtI2a4eB4UpUJ6m4zBOoE2TrJMDdYddCuskPKd8MRzIRf2mjzjH3L8/DHJ9CK71qYE6lLrtjVrsyJg7G2ztfTmH8xMtr6UrLWWnAQl5xuGGfMiywoM8w4VXA4UgKV2/K2TXr5i5ZlobcqGFuiXdtD6CqQQy6K6GQmqmLK0PbYOGN9mhcBa0U1zOPx/yVgNE5iPFq9LfTTeEw92MfMvnF8VD4fC74bqkbpTPgYo/+HExeBOujMf8PFSS/0U0gIiQff5eYQQR13iyS/PEsGAsVVxL+NlJcZtMRXVcpt5GK7K/kyCoNToqfXyrYD8hknccAYxLchhU4GjnM6eUxxRQpvUSboISsucq3wrxFIIrFicQylqtbRIZB1Gq1GnnAhSPMQHJWSzejY5/OLzMPkdzy8Lqj2eGXuOxrkCS06fu5b8wRqVeyLhlxDJ9BnJynDDjqkvsfznF0+BQJdiOf7l2AS0isjVBwd210rnOkJ0M=
  file: mewpoke*
  skip_cleanup: true
