language: java
dist: trusty
script:
  gradle build
deploy:
  provider: releases
  api_key:
    secure: h1DX6VBQt0cdCYCttuPv9tBnWqZL0S8xbVipzJS9S8kpyXzYoZxhTAAAZC/ScdnJ5p9PR6STOY00q02b8jJjLKh76pJwri9D0nYtjnv21rEYNrovlSwvfMJJ5PeP7Xfyeddon+6Ylu41tAb3AQWS2ptRjXmEWJPeVR2ynW0ZGt7qaAyp3vijy28yLvhWuMn/4kUVuNafYemGA1LCJEXxxOYvIcZ0cxod8Qs0UOQz4PE+CRzyDhMuUZ1QCCtX9rqiknyl5mcE5MmSqf1tJRYUbhKckCuk1SlZheXm/mtr1kub3VbuwXOQ3+kuVSwoOhMqAWjDxr876Tpbq08yW0F51MuXrce+d5TIitf0WO/E5tQiNC/Dv+oJZX6P8wEGBtpYoPq+y4YqhLx4uE6QVo/bcsntDv9KW/sPzOKe9KLlw6aRz8LnhV5+lw59GnVq/vwbF4P98RQK33K1e+rIo4gj6O9lChkq1w8BGYLvI/Y8uri/pjozIMDoUCe9UcdC8VPdagI3ZVkT53T1Ze4FahehJsg71aFWoBpOY69pNC4/HPxJAhakG+wRtAJKDtDfmSR12gRc3bK6Eb8vTRCTSrmFOOS2v/QHoBzirijiLGJ1Ro161xvNPmd9Ww7lX+h5C639+qaiRBCW/BmXzGdDSDS3P4uEQU+BvFfyvclkoXQM8c=
  file: build/libs/mewpoke*
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
    repo: criteo/mewpoke
